### PR TITLE
Defect nycchkbk 10629: M/WBE Transaction Page - Center align text for Women and Emerging business

### PR DESCRIPTION
**Pull request by nranevj**
- Center align text for Women and Emerging business and other columns for contracts transaction page

### CODE REVIEW

**Review by sgade-reisys — CHANGES_REQUESTED** [review]
@nranevj , can you please use existing CSS?

**Comment by nranevj** [comment]
> @nranevj , can you please use existing CSS?

Modified code to use existing CSS. Have added two new CSS rules that are required to solve this issue.

**Comment by nranevj** [comment]
> @nranevj , can you please use existing CSS?
Modified code to use existing CSS. Have added two new CSS rules that are required to solve this issue.

**Comment by nranevj** [comment]
Will modify code to use 'add dummy column' implementation and will make a new PR.

**Pull request closed without merging**
