### PR TITLE
NYCCHKBK-10301: Data feeds Spending Citywide - Payee Name autopopulation issue

### PR DESCRIPTION
**Pull request by nranevj**

### CODE REVIEW

**Review by KavithaG-REISys — COMMENTED** [review]
Datafeeds citywide spending payee name has code in the drop down. Please verify the codes are displayed.

**Review by sgade-reisys — CHANGES_REQUESTED** [review]
We display name code combination in Data-feeds auto-suggestions.  Is there any exception for payee name?

**Comment by nranevj** [comment]
In Data feeds Spending Citywide, the ‘payee name’ field is mapped to ‘vendor_name_code’ field in Solr. But, for a few records in Solr, the ‘vendor_name_code’ field itself doesn’t exist (they have only ‘vendor_name’ field), due to which such records don’t show up in autocomplete suggestions.  

Whereas in Advanced search, ‘payee name’ is mapped to ‘vendor_name’ field, so we see all entries, but we don’t see the code for it next to the name in autocomplete suggestions. The same is implemented in Data feeds Spending OGE as well.

  **_Example:_**
   Agency: Board of Correction
Department: PERSONAL SERVICES
Expense Category: Payroll Summary
Payee Name: PERSONAL SERVICES

**Comment by sgade-reisys** [comment]
> In Data feeds Spending Citywide, the ‘payee name’ field is mapped to ‘vendor_name_code’ field in Solr. But, for a few records in Solr, the ‘vendor_name_code’ field itself doesn’t exist (they have only ‘vendor_name’ field), due to which such records don’t show up in autocomplete suggestions.  
> 
> Whereas in Advanced search, ‘payee name’ is mapped to ‘vendor_name’ field, so we see all entries, but we don’t see the code for it next to the name in autocomplete suggestions. The same is implemented in Data feeds Spending OGE as well.
> 
>   **_Example:_**
>    Agency: Board of Correction
> Department: PERSONAL SERVICES
> Expense Category: Payroll Summary
> Payee Name: PERSONAL SERVICES


Can you make sure the requirement to display auto-suggestions for Payee name.  Also, can you please provide the Solr queries where you see vendor name exists but vendor name code does not?

**Comment by nranevj** [comment]
The following is a query which gives records where vendor_name exists but vendor_name_code does not:

http://sdw5.reisys.com:18985/solr/checkbook_dev.public.solr_citywide/select?fq=domain:spending&q=expenditure_object_name:%22Payroll%20Summary%22%20AND%20department_name:%22PERSONAL%20SERVICES%22%20AND%20agency_name:%22BOARD%20OF%20CORRECTION%22

For solr admin, you can use the following parameters:

q: expenditure_object_name:"Payroll Summary" AND department_name:"PERSONAL SERVICES" AND agency_name:"BOARD OF CORRECTION"

fq: domain:spending

**Comment by nranevj** [comment]
As per the ticket requirement, have made the following changes to handle the missing autocomplete suggestions for payee name field:
- If the number of results (from vendor_name_code fetch query) are less than 10, fetch records having ‘vendor_name’ attribute from Solr satisfying the given criteria. 
- Add these to the final result, but ensure that the total results are less than or equal to 10, and there are no duplicates.

**Comment by nranevj** [comment]
Will need to confirm why the database doesn't have vendor code for a few entries.

**Pull request closed without merging**
