### PR TITLE
NYCCHKBK 10429 : MWBE Spending Data feeds form and results page

### PR DESCRIPTION
**Pull request by nranevj**
Added woman owned and emerging business columns in the form as well as results

### CODE REVIEW

**Review by sgade-reisys — CHANGES_REQUESTED** [review]
@nranevj, can you please check if the search criteria for woman owned business needs to be changed to 'woman_owned_business'?

**Review by sgade-reisys — CHANGES_REQUESTED** [review]
@nranevj, can you please take care of the minority category mapping?

**Comment by nranevj** [comment]
> @nranevj, can you please take care of the minority category mapping?

I have taken care of minority category mapping

**Comment by nranevj** [comment]
> @nranevj, can you please check if the search criteria for woman owned business needs to be changed to 'woman_owned_business'?

I have updated it to 'woman' owned.

**Review by KavithaG-REISys — APPROVED** [review]

**Review by sgade-reisys — APPROVED** [review]

**Pull request merged**
